#!/bin/zsh
mkdir /tmp/Pictures
import /tmp/Pictures/screenshot.jpg
xclip -se c -t image/jpg -i /tmp/Pictures/screenshot.jpg


# send image through adb
adb push /tmp/Pictures/screenshot.jpg sdcard/DCIM/camera
